Adds periodAndDuration constructor using a periodAndDuration value.
microsoft/kiota-java pull request #577
Opened 2023-08-15 17:41 UTC by ramsessanchez

Related to https://github.com/microsoft/kiota/pull/3128

2023-08-15 17:48 UTC, ramsessanchez commented
@baywet @andrueastman  would this constitute a minor version bump?

2023-08-15 18:21 UTC, baywet requested changes
yes please bump the patch (such a minor change) + changelog entry

2023-08-20 19:55 UTC, baywet approved these changes

2023-08-21 06:25 UTC, andrueastman approved these changes

2023-08-21 18:36 UTC, merged